### ISSUE TITLE
Update mauve-sim to account for final workflow

### ISSUE THREAD

**Issue by RangerMauve** [playproject-io/datdot-service#10]
- [x] Change p2plex to enable listening on channel and filtering incoming by key
- [x] Change hosterAddFeed to download instead of request encoding
- [x] Add encoder public key to hosterAddFeed, use to generated shared channel
- [ ] Add event to hoster for notifying chain when it's got an encoded chunk
- [x] Have encoder generate shared channel to send data through
- [x] Update mauve-mvp with new flow, have chain choose encoder and hoster and notify them

**Comment by serapath** [comment]
> @ninabreznik:
> 1. Emit shared event (pubKeys of selected hosters and pubKeys of selected encoders)
> 2. Encoding 
> 3. Joining the swarm (swarmkey derived from hoster-encoder pubKeys => shared channel)
> 4. Hoster notifies chain that they are done
