### ISSUE TITLE
use isInBlock instead of isFinalized

### ISSUE THREAD

**Issue by joshua-mir** [playproject-io/datdot-service#4]
what was previously named "isFinalized" is now named "isInBlock" - (isFinalized now actually triggers on finality, not block inclusion), we probably want to respond to events when they are isInBlock, not isFinalized.

super-long-term, a more robust mechanism would wait for finality and retry actions if finality is not achieved before dropping the extrinsic callback.

**Comment by ninabreznik** [comment]
Ok, so I am pulling new version of datdot-substrate, building it and then changing in datdot-service isFinalized to isInBlock and will first try if all still works. If yes, I continue with adding js part for the attestation.
